# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
   
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source

    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: npm install&build    
      run: |    
        npm ci
        npm run build --if-present
        npm test
    - name: Deploy with gh-pages  
      uses: JamesIves/github-pages-deploy-action@v4.4.2
      with:
        branch: gh-pages
        folder: build # The folder the action should deploy. 
    # - run: |
    #     git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
    #     npm run deploy -- -u "github-actions-bot <support+actions@github.com>"
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}